/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithoutNavRouteImport } from './routes/_withoutNav'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCharactersIndexRouteImport } from './routes/_app/characters/index'
import { Route as AppAboutIndexRouteImport } from './routes/_app/about/index'
import { Route as WithoutNavCharactersAddRouteImport } from './routes/_withoutNav/characters.add'
import { Route as AppCharactersCharacterIdRouteImport } from './routes/_app/characters/$characterId'

const WithoutNavRoute = WithoutNavRouteImport.update({
  id: '/_withoutNav',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCharactersIndexRoute = AppCharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutIndexRoute = AppAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AppRoute,
} as any)
const WithoutNavCharactersAddRoute = WithoutNavCharactersAddRouteImport.update({
  id: '/characters/add',
  path: '/characters/add',
  getParentRoute: () => WithoutNavRoute,
} as any)
const AppCharactersCharacterIdRoute =
  AppCharactersCharacterIdRouteImport.update({
    id: '/characters/$characterId',
    path: '/characters/$characterId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/characters/add': typeof WithoutNavCharactersAddRoute
  '/about/': typeof AppAboutIndexRoute
  '/characters/': typeof AppCharactersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/characters/add': typeof WithoutNavCharactersAddRoute
  '/about': typeof AppAboutIndexRoute
  '/characters': typeof AppCharactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_withoutNav': typeof WithoutNavRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/characters/$characterId': typeof AppCharactersCharacterIdRoute
  '/_withoutNav/characters/add': typeof WithoutNavCharactersAddRoute
  '/_app/about/': typeof AppAboutIndexRoute
  '/_app/characters/': typeof AppCharactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/characters/$characterId'
    | '/characters/add'
    | '/about/'
    | '/characters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/characters/$characterId'
    | '/characters/add'
    | '/about'
    | '/characters'
  id:
    | '__root__'
    | '/_app'
    | '/_withoutNav'
    | '/_app/'
    | '/_app/characters/$characterId'
    | '/_withoutNav/characters/add'
    | '/_app/about/'
    | '/_app/characters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  WithoutNavRoute: typeof WithoutNavRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_withoutNav': {
      id: '/_withoutNav'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WithoutNavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/characters/': {
      id: '/_app/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof AppCharactersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about/': {
      id: '/_app/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AppAboutIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_withoutNav/characters/add': {
      id: '/_withoutNav/characters/add'
      path: '/characters/add'
      fullPath: '/characters/add'
      preLoaderRoute: typeof WithoutNavCharactersAddRouteImport
      parentRoute: typeof WithoutNavRoute
    }
    '/_app/characters/$characterId': {
      id: '/_app/characters/$characterId'
      path: '/characters/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof AppCharactersCharacterIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCharactersCharacterIdRoute: typeof AppCharactersCharacterIdRoute
  AppAboutIndexRoute: typeof AppAboutIndexRoute
  AppCharactersIndexRoute: typeof AppCharactersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCharactersCharacterIdRoute: AppCharactersCharacterIdRoute,
  AppAboutIndexRoute: AppAboutIndexRoute,
  AppCharactersIndexRoute: AppCharactersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WithoutNavRouteChildren {
  WithoutNavCharactersAddRoute: typeof WithoutNavCharactersAddRoute
}

const WithoutNavRouteChildren: WithoutNavRouteChildren = {
  WithoutNavCharactersAddRoute: WithoutNavCharactersAddRoute,
}

const WithoutNavRouteWithChildren = WithoutNavRoute._addFileChildren(
  WithoutNavRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  WithoutNavRoute: WithoutNavRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
